### ISSUE TITLE
AttributeError: module 'platformio.util' has no attribute 'load_project_config':

### ISSUE THREAD

**Issue by r0oland** [platformio/bintray-secure-ota#12]
And here is another one...
`AttributeError: module 'platformio.util' has no attribute 'load_project_config':`
This happens when calling 
`project_config = util.load_project_config()
`
in publish_firmware.py.

Any hints?

**Comment by r0oland** [comment]
Seems this way of using util is no longer supported, but for me changing 

```
 from platformio import util
 project_config = util.load_project_config()
 bintray_config = {k: v for k, v in project_config.items("bintray")}
 version = project_config.get("common", "release_version")
```
to 
```
try:
    import configparser
except ImportError:
    import ConfigParser as configparser
project_config = configparser.ConfigParser()
project_config.read("platformio.ini")
version = project_config.get("common", "release_version")
bintray_config = {k: v for k, v in project_config.items("bintray")}
```
as per https://docs.platformio.org/en/latest/projectconf/advanced_scripting.html#custom-options-in-platformio-ini

**Comment by ivankravets** [comment]
Yes, this is the right way. Could you provide a PR and we will merge? Thanks!

**Comment by r0oland** [comment]
This is my first time actually doing a PR, so I hope I did it right...

**Comment by ivankravets** [comment]
Yes, you did everything correctly! Thanks and congrats on the first PR :)
