### ISSUE TITLE
Rework BintrayClient.cpp to match with ArduinoJson >= v.6x 

### ISSUE THREAD

**Issue by cyberman54** [platformio/bintray-secure-ota#15]
BintrayClient.cpp is using ArduinoJson 5.x. This makes it difficult to integrate bintray-secure-ota in projects which use/need ArduinoJson 6.x.

**Comment by cyberman54** [comment]
I suggested a solution with PR #16

**Comment by ivankravets** [comment]
Thanks! Merged.
