### ISSUE TITLE
Can't upload firmware files

### ISSUE THREAD

**Issue by cyberman54** [platformio/bintray-secure-ota#2]
I'm trying to upload firmware files with platformIO, but i always run on error:

```
CURRENT: upload_protocol = custom
Uploading .pioenvs\release\firmware_v_1.bin
Uploading firmware_v_1.bin to Bintray. Version: 1
Failed to submit package: 401
{"message":"This resource requires authentication"}
```

API-token is set in `platformio.ini`

**Comment by ivankravets** [comment]
Have you resolved this issue?

**Comment by cyberman54** [comment]
No. I have no idea how to.

**Comment by ivankravets** [comment]
I see. Your repository on Bintray is private. There is no implementation of authentication here https://github.com/platformio/bintray-secure-ota/blob/master/lib/BintrayClient/src/BintrayClient.cpp#L81
If your repository is public, you can use API without authentication. Could you send us PR with this feature? It should not be difficult.

Just need to implement HTTP Basic Authentication, see https://bintray.com/docs/api/#_authentication

P.S: There is no sense to have a private repository to keep compiled firmware binaries. Nevertheless, it should be easy to add HTTP Basic Authentication

**Comment by cyberman54** [comment]
Thanks for explanation, i thought my bintray repo would be public. Downloads should be public, but only i want to able to upload new code via platformio. I thought this would be the purpose of the API key.

Looks like i need to dive deeper in the concept to understand it.

**Comment by cyberman54** [comment]
@ivankravets I still could'nt solve this. I double checked that the repository in Bintray is public, not private. Using the bintray settings in "Edit Repository - General Settings", the repository is marked public.

**Comment by cyberman54** [comment]
@ivankravets i downgraded m y bintray enterprise trial account to the free open source account, and after this reinstalled the bintray repository. Now upload and download are working as expected. Thanks for the example. Closing this issue now.
