### ISSUE TITLE
How can i use dynamic variable for package in bintray section in platformio.ini?

### ISSUE THREAD

**Issue by cyberman54** [platformio/bintray-secure-ota#3]
I want to select package name for bintray upload path in platformio.ini by using the current environment name.

e.g.

[env:esp32heltec]
...

[bintray]
package = ${sysenv.PIOENV}

but this does not work this way.

**Comment by ivankravets** [comment]
Did you set PIOENV before? Or, do you mean internal PlatformIO PIOENV build variable?

**Comment by cyberman54** [comment]
I want to access the environment name, "esp32heltec" in the above example.

**Comment by ivankravets** [comment]
Could you try to change [this line](https://github.com/platformio/bintray-secure-ota/blob/master/publish_firmware.py#L22) from `bintray_config = {k: v for k, v in project_config.items("bintray")}` to `bintray_config = {k: env.subst(v) for k, v in project_config.items("bintray")}`

Now, just use 
```
[bintray]
package = $PIOENV
```

Does it work?

**Comment by cyberman54** [comment]
I solved it in the python script this way:

```
project_config = util.load_project_config()
bintray_config = {k: v for k, v in project_config.items("bintray")}
version = project_config.get("ota", "release_version")
package = env.get("PIOENV")
```
